name: Check
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Create package-lock
      run: npm install
    - name: Install deps
      run: npm ci
    - name: Lint
      run: npm run lint
